### ISSUE TITLE
Banned player can join 

### ISSUE THREAD

**Issue by pkowalski99** [RedAlex/FiveM-BanSql#10]
I ban user properly, banned user is on correct table but he still can join to server with no error.

**Comment by RedAlex** [comment]
A have an idea, i will make it soon as possible. Loot of real work for the moment.

**Comment by pkowalski99** [comment]
Already repair it. 'brake' in loop when player connecting was the problem

**Comment by pkowalski99** [comment]
`AddEventHandler('playerConnecting', function (playerName,setKickReason)
    local steamID  = GetPlayerIdentifiers(source)[1]
	local license  = GetPlayerIdentifiers(source)[2]
	local playerip = GetPlayerIdentifiers(source)[3]

	
	--Si Banlist pas chargée
	if (Banlist == {}) then
		Citizen.Wait(1000)
	end

    if steamID == false then
		setKickReason("Vous devez ouvrir steam !")
		CancelEvent()
    end
	
	for i = 1, #BanList, 1 do
		if ((tostring(BanList[i].identifier)) == tostring(steamID) or (tostring(BanList[i].license)) == tostring(license) or (tostring(BanList[i].playerip)) == tostring(playerip)) and (tonumber(BanList[i].expiration)) > os.time() and (tonumber(BanList[i].permanent)) == 0 then
			local tempsrestant     = (((tonumber(BanList[i].expiration)) - os.time())/60)
				if tempsrestant >= 1440 then
					local day        = (tempsrestant / 60) / 24
					local hrs        = (day - math.floor(day)) * 24
					local minutes    = (hrs - math.floor(hrs)) * 60
					local txtday     = math.floor(day)
					local txthrs     = math.floor(hrs)
					local txtminutes = math.ceil(minutes)
						setKickReason("Vous etes banni pour : " .. BanList[i].reason .. Text.timeleft .. txtday .. Text.day ..txthrs .. Text.hour ..txtminutes .. Text.minute)
						CancelEvent()
				elseif tempsrestant >= 60 and tempsrestant < 1440 then
					local day        = (tempsrestant / 60) / 24
					local hrs        = tempsrestant / 60
					local minutes    = (hrs - math.floor(hrs)) * 60
					local txtday     = math.floor(day)
					local txthrs     = math.floor(hrs)
					local txtminutes = math.ceil(minutes)
						setKickReason("Vous etes banni pour : " .. BanList[i].reason .. Text.timeleft .. txtday .. Text.day .. txthrs .. Text.hour .. txtminutes .. Text.minute)
						CancelEvent()
				elseif tempsrestant < 60 then
					local txtday     = 0
					local txthrs     = 0
					local txtminutes = math.ceil(tempsrestant)
						setKickReason("Vous etes banni pour : " .. BanList[i].reason .. Text.timeleft .. txtday .. Text.day .. txthrs .. Text.hour .. txtminutes .. Text.minute)
						CancelEvent()
				end
		end
	
		if ((tostring(BanList[i].identifier)) == tostring(steamID) or (tostring(BanList[i].license)) == tostring(license) or (tostring(BanList[i].playerip)) == tostring(playerip)) and (tonumber(BanList[i].permanent)) == 1 then
			setKickReason(Text.yourpermban .. BanList[i].reason)
			CancelEvent()
		end
	
		if ((tostring(BanList[i].identifier)) == tostring(steamID) or (tostring(BanList[i].license)) == tostring(license) or (tostring(BanList[i].playerip)) == tostring(playerip)) and (tonumber(BanList[i].expiration)) < os.time() and (tonumber(BanList[i].permanent)) == 0 then
			deletebanned(steamID)
		end
	
		--break
	end
	
end)`

This break what i comment

**Comment by pkowalski99** [comment]
btw awesome plugin, love it :D I make autoban system with this, thank you :)

**Comment by RedAlex** [comment]
Bug fix.
https://github.com/RedAlex/FiveM-BanSql/commit/195fccd0298e4c900e277a1c96c7dacdf1be6200
