### ISSUE TITLE
Commands can be use by console

### ISSUE THREAD

**Issue by RedAlex** [RedAlex/FiveM-BanSql#21]
- [ ] Rebuild permission system to use register command.
- [ ] Change all es:addcommandgroup to register command.
- [ ] in register get source if source == 0 then else get source group or perm lvl?
- [ ] Do some test!!

**Comment by techniciantucker** [comment]
Will this ever be completed / implemented? It'd be amazing to not have to go into the city to offline someone and just execute it via the console / rcon..

**Comment by RedAlex** [comment]
https://github.com/RedAlex/FiveM-BanSql/commit/3c67945c35acae70ee8c3533710f91814ea26529
