### ISSUE TITLE
Banoffline reason

### ISSUE THREAD

**Issue by Jordanpkl** [RedAlex/FiveM-BanSql#22]
When I try to ban someone offline it says the duration, but when I try to write the reason it says "player ID incorrect" 
![image](https://user-images.githubusercontent.com/45295750/53126998-b5d13f80-3561-11e9-9f66-7ec4fc7635f7.png)

**Comment by RedAlex** [comment]
The ban offline use the new sql Database.
Have you migrate it?
If yes the Player you want to ban need to be connected 1 time after the migrate

**Comment by Jordanpkl** [comment]
Oh, okay, so my problem is that the player didn't connect before the migrate, also if I migrate, all bans that I had still work right?

**Comment by RedAlex** [comment]
yes

**Comment by Jordanpkl** [comment]
I updated it right now. And it's giving me an error on server.lua:42 
![image](https://user-images.githubusercontent.com/45295750/53129310-832a4580-3567-11e9-97bb-5cb929051955.png)

**Comment by RedAlex** [comment]
Have you update your config.lua?

**Comment by RedAlex** [comment]
and _ressource.lua

**Comment by Jordanpkl** [comment]
yep, and still giving an error

**Comment by RedAlex** [comment]
Can you try to update all file again,
type refresh in your server console
and restart FiveM-BanSql
Or reboot the server

If not work you can contact me on discord i will help you to find the error

**Comment by Jordanpkl** [comment]
I reboot my server and it worked, thank you 😃

**Comment by RedAlex** [comment]
You welcome.
