### ISSUE TITLE
Database problem in MariaDB

### ISSUE THREAD

**Issue by SliderKP** [RedAlex/FiveM-BanSql#23]
MariaDB - CentOS 7.5
when i try to import my ban database i get this error:

"invalid default value for 'added' "

i tried to solve with google but... i cant :/

the problem are here:
  `added` datetime DEFAULT CURRENT_TIMESTAMP,

**Comment by RedAlex** [comment]
You can remove this info and have no impact on the ressource. You just don't see the date the data will be add in your database

**Comment by SliderKP** [comment]
yes, this solve my problem, but when i try to use /sqlbanhistory i getting a error:
thanks for your answer

http://puu.sh/DKRqJ/a844da9bcb.jpg
