### ISSUE TITLE
Request: Maybe add HWID ban ? :)

### ISSUE THREAD

**Issue by Tinky124** [RedAlex/FiveM-BanSql#36]
Maybe to add HWID ban if is possible?

**Comment by iSentrie** [comment]
Not possible without some external program.

**Comment by Tinky124** [comment]
@XvenDeR its possible look at: https://github.com/Blumlaut/EasyAdmin/commit/4b30b9ad4913779e0fc24f28fa11dfb395e2b717

**Comment by iSentrie** [comment]
Hm, yes `GetPlayerToken` is something to that side, but it varies per server I heard.
